#  _                _     _
# | |              | |   | |
# | |    _   _  ___| |__ | |_ __ _
# | |   | | | |/ __| '_ \| __/ _` |
# | |___| |_| | (__| | | | || (_| |
# |______\__,_|\___|_| |_|\__\__,_|
# Copyright (c) 2022 by Dev7ex
# Version: 1.1.0

settings:
  chat-enabled: true
  chat-format: '%prefix% %name% §8» §7%message%'
  tablist-enabled: true
  # Should all players with the permission (luchta.update.notify)
  # get a update notification message when entering server
  update-message: true